### ISSUE TITLE
Erreur Java - caractère illégal " / " - URL agenda google

### ISSUE THREAD

**Issue by DtNeo** [axelor/axelor-open-suite#5651]
Bonjour,

Je souhaite synchroniser mon agenda google mais une erreur sur les caractères dans l'url de l'agenda google bloque la configuration.
Je précise que tous les élements de sécurités sont bons, et que seul l'information de l'url bloque la synchronisation du bon agenda.

Axelor Open Suite - Axelor Entreprise Application
Version: 5.3.7

**Connexion réussite à google agenda avec url simple :** 
calendar.google.com

**Connexion en erreur lors que je précise l'url complète :** 
https://calendar.google.com/calendar/embed?src=***%40***.com&ctz=Europe%2FParis

**Connexion en erreur lors que je précise une "petite" l'url :** 
https://calendar.google.com

### Erreur dans le traceback : 
**Anomalie**
java.net.MalformedURLException: Illegal character found in host: '/'
**Erreur**
java.net.URL.<init>(URL.java:429)
**Message**
Illegal character found in host: '/'
**Trace**
java.net.MalformedURLException: Illegal character found in host: '/'
	at java.net.URL.<init>(URL.java:429)
	at java.net.URL.<init>(URL.java:312)
	at com.axelor.apps.base.ical.ICalendarService.testConnect(ICalendarService.java:189)
	at com.axelor.apps.base.web.ICalendarController.testConnect(ICalendarController.java:95)
	at sun.reflect.GeneratedMethodAccessor2437.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...

Merci pour votre aide et bonne continuation

**Comment by DtNeo** [comment]
CE N'EST PAS UNE ERREUR SOFTWARE !

SOLUTION UNIQUE : 
Connexion réussite à google agenda avec url simple :
calendar.google.com
```
Pensez ensuite à réaliser cette étape : 
Actions > Synchroniser le calendrier
```

- [ ] Pour les modos : 

Veuillez ajouter cette IMPERATIVE étape à faire dans la description de la documentation
https://docs.axelor.com/abs/5.0-fr/functional/calendrier.html#synchroniser-un-calendrier

Excellente journée
