### ISSUE TITLE
Error :Cannot invoke method plusWeeks() on null object on stock module

### ISSUE THREAD

**Issue by dalmed** [axelor/axelor-open-suite#8761]
Error on [Stock management] -> [Stock moves] -> [Supplier arrivals] and [Supplier return] :
**Cannot invoke method plusWeeks() on null object**

trace : 
java.lang.NullPointerException: Cannot invoke method plusWeeks() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:165) ...

**Comment by ale-axelor** [comment]
Hello,

This error can happen when `context.date` is missing: see fac81a6a2eebdffe294921d752c3ced883e5570b
Does the issue still happen after updating your application.properties to add missing properties ?
